[[redirects]]
  from = "https://dj.jela.io"
  to = "https://soundcloud.com/beryju"
  status = 301
  force = true

[[redirects]]
  from = "/v2"
  to = "https://jela.io/.netlify/functions/oci-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/v2/*"
  to = "https://beryju.docker.scarf.sh/v2/beryju/:splat"
  status = 200
  force = true
