name: docker build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to beryju.org Container Registry
        uses: docker/login-action@v1
        with:
          registry: beryju.org
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Building Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: beryju.org/jens/jela.io:latest
          context: .
