name: notify
on:
  push:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .stable.version version.json -r'

      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: authentik Release bot
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'authentik version ${{ steps.version.outputs.value }} has been released.'
